#!/bin/bash

# Display cheat codes for reference
echo "Termux Cheat Codes:"
echo "______________________"
echo "nano       : Open GNU nano text editor."
echo "______________________"
echo "o          : List all files and folders in detailed format."
echo "______________________"
echo "ll         : List all files and folders in detailed format (including hidden)."
echo "______________________"
echo "pwd        : Print the current working directory."
echo "______________________"
echo "ls         : List all files and folders."
echo "______________________"
echo "l          : List all files and folders in a compact format."
echo "______________________"
echo "la         : List all files and folders (including hidden) in a compact format."
echo "______________________"
echo "rm         : Remove files or directories."
echo "______________________"
echo "cls        : Clear the screen."
echo "______________________"
echo "cp         : Copy files or directories."
echo "______________________"
echo "mv         : Move files or directories."
echo "______________________"
echo "mkdir      : Create a directory."
echo "______________________"
echo "rmdir      : Remove a directory."
echo "______________________"
echo "touch      : Create a new file."
echo "______________________"
echo "cat        : Display the contents of a file."
echo "______________________"
echo "grep       : Search for patterns in files."
echo "______________________"
echo "head       : Display the beginning of a file."
echo "______________________"
echo "tail       : Display the end of a file."
echo "______________________"
echo "chmod      : Change permissions of a file or directory."
echo "______________________"
echo "chown      : Change owner of a file or directory."
echo "______________________"
echo "df         : Display disk usage."
echo "______________________"
echo "du         : Display disk usage of files and directories."
echo "______________________"
echo "tar        : Compress or extract files."
echo "______________________"
echo "unzip      : Extract files from a zip archive."
echo "______________________"
echo "ping       : Send ICMP Echo Request packets to network hosts."
echo "______________________"
echo "ifconfig   : Display network interface configuration."
echo "______________________"
echo "ssh        : Connect to a remote server using SSH."
echo "______________________"
echo "wget       : Download files from the internet."
echo "______________________"
echo "curl       : Transfer data from or to a server."
echo "______________________"
echo "top        : Display and update sorted information about processes."
echo "______________________"
echo "ps         : Display information about processes."
echo "______________________"
echo "kill       : Terminate processes."
